Proposing a new code layout & style.
mudlee/spck pull request #6
Opened 2021-02-25 12:25 UTC by andreihu

2021-02-25 16:32 UTC, mudlee requested changes

2021-02-25 16:32 UTC, mudlee commented on CMakeLists.txt
> +add_subdirectory(src)
I get an error, possibly for this line when I try to build it by running `./spck.sh -install && ./spck.sh -build`
```bash
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /Users/mudlee/Work/spck/src

  does not contain a CMakeLists.txt file.
```

2021-02-25 16:32 UTC, mudlee commented on src/sandbox/main.cpp
> +#include "sandbox.hpp"
Shouldn't it be?
```c++
#include <sandbox.hpp>
```

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/api.hpp
> +#ifdef SPCK_PLATFORM_WINDOWS
Wouldn't look this better in this way?
```c++
#ifdef SPCK_PLATFORM_WINDOWS
    #ifdef SPCK_BUILD_DLL
        #define SPCK_API __declspec(dllexport)
    #else
        #define SPCK_API __declspec(dllimport)
#endif
#else
    #define SPCK_API
#endif
```

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/application.hpp
> +class SPCK_API application {
These three lines (namespace, class, public) after each and other just makes it hard to read.
Can we use a convention that at least between namespace and class you have to have an empty line?
```c++
namespace spck {

class SPCK_API application {
}

}

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/messaging/application_event.hpp
> +#include "event.hpp"
`#include <event.hpp>` ?

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/messaging/key_event.hpp
> +#include "event.hpp"
`#include <event.hpp>`?

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/spck.hpp
> +#include "application.hpp"
Shouldn't we use <>?

2021-02-25 16:32 UTC, mudlee commented on src/spck/spck/window/window.cpp
> +#include "window.hpp"
Shouldn't we use <>?

2021-02-25 19:12 UTC, andreihu commented on CMakeLists.txt
> +add_subdirectory(src)
If the CMakeLists.txt file is there, then you might want to try to delete the build folder and start from scratch.

2021-02-25 19:14 UTC, andreihu commented on src/sandbox/main.cpp
> +#include "sandbox.hpp"
That'll become an include error.

2021-02-25 19:15 UTC, andreihu commented on src/spck/spck/api.hpp
> +#ifdef SPCK_PLATFORM_WINDOWS
It was clang-format which is formatting down to this style. I'll try to improve it.

2021-02-25 19:16 UTC, andreihu commented on src/spck/spck/application.hpp
> +class SPCK_API application {
I'll try to improve it.

2021-02-25 19:16 UTC, andreihu commented on src/spck/spck/messaging/application_event.hpp
> +#include "event.hpp"
That's gonna end up with a missing header error.

2021-02-25 19:16 UTC, andreihu commented on src/spck/spck/messaging/key_event.hpp
> +#include "event.hpp"
That's gonna end up with a missing header error.

2021-02-25 19:17 UTC, andreihu commented on src/spck/spck/spck.hpp
> +#include "application.hpp"
That's gonna end up with a missing header error.

2021-02-25 19:17 UTC, andreihu commented on src/spck/spck/window/window.cpp
> +#include "window.hpp"
That's gonna end up with a missing header error.

2021-02-26 09:21 UTC, mudlee approved these changes

2021-02-26 09:23 UTC, merged